language: java
#dist: trusty
#group: edge
#sudo: false

env:
  global:
      #travis encrypt -r gchq/event-logging GH_USER_AND_TOKEN="*****"
      #where ***** is '<github username>:<github personal access token>'
      #Required for curling the gh api to get the source of the latest event-logging release
    - secure: "Dj0AtkItxitrOijaZc/STz/3oUyGBNaB6k3yhgZI3Fw2MDHqqV073nr5xWPawrP2AyQmRE8zRgrvLH7ZpjBcQiJnC2qYBho8Ap5ZpwtQJ6XMpPvKhlG9mXl8CQ31n0gukxJj3jSJn/+R3MPNYPxCUcQ87wOMnveY+0bJhWpfbsJKN/2OMpIc2yie2MUcJ9OpzeSfx/LekxZsTsNai6gMwB6l4l44gB2sBRPL5I3a6UFQHNS1+Z5qrlYraS2KvL2X20nfGG2SpbVfaJneNqISjPUKIsNfR1LYre/nJDSWxCpYjZfuqt6OoH9yUg/jmmKt6Y3+mF4x8/GavOs76ImBeaqBWX/esuyAQEOCfW2pcv2r6EdpGA9BQMCOi1SoEAiJC2kND4Sy+HtEkZ0xVBrAvFT/2v1F5BPu9POzsfw55R5RbwDrBO+N4zMaPtxlo7eUEJ+vPKxOgVJrU9qEIR/GEnwv3z5FXT1YxkmksWjxuXLxZlCO0NHYfB4uwdogmhD9B8dk+ZeF1fee7U088ytsvAk89cQde0CZm9n4by98gwmcopUzyQSuYaxhQHoI9sV9hCaFNwlMXwd39vO8Zbi6Wvf2upAzkgDBwG0SWMDFXppcfT7zxcYQMlouDsFpDLXqnEYTdqEJtSgSLoMCq+LXITzc+FaKu8I127USQIcikwY="

#addons:
  #apt:
    #packages:
    #- oracle-java8-installer

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
      - env: JDK='OpenJDK 10'
        install: . ./install-jdk.sh -F 10 -L GPL

install: echo "skip 'gradle assemble' step to speed up build"

script: ./travis.script.sh

# Push to GitHub releases - the key was generated by the Travis CLI.
deploy:
  provider: releases
  api_key:
    secure: jR0YRPUW0TR288Vqq610yWYyxW3DkBgw9TfWYg/wn46xskMtENxP3pFIQ9AcDvmpw3O9wUHTKzn/JSvv3sEQifNiQwZAqkX+4uJ3RPM7m/4tos23J5Wm1Y7aLiJv52TJEzA4U1ZUt5NE9cs4XwrowvdhzgA5YevlY/H6IEVYmZ5xSgsE3DNrRb+i6QHnJee58/3ZfPsLzM0u4ha4JAi4CpQC6Dp9EvcpOKAZjV2W4E8OrwEcO1wO9zwGG77ieZPcTVhH08cBLTXSw2YH0BK4CaHN9z3NhuCUCdFsobVY9HZpFWP5/ZhfpNfbxkREMFyCgNeBNMXG3KFhAZbqJNJ6BpBWcLUflAwDG50xObLgh6DU0QD/ZK/4+m0Vb05bnHv8dr98QBQgU+amx1UhMaRGrmLSxJwcCFNmnn8Kl6NJWYFjfcW/vqf8nDcywXNUSImjHCXVMj+uGQNfn5YrBsMERsYrB9ytUu6tQCqS+jGkq85n/wnCMscD7xV+S1i8w/dEBpa65jxPFrGl3VF6NXfi3dtH4AbFKFsLsI07mF2E6CfsyD5JWJBH/UoUe6FW+2BA7pYFZRic9YzyZTcJs6R1ZScwuV7d3NJsVoqPhLpVQyph6ctS/4nmB4wR8ZhPD3Rh67MRi8NbZNx9KjidRp/0DCmsEjXWHYyasBgUtXZd2sU=
  file_glob: true
  file: event-logging-api/build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
