language: java
dist: trusty
group: edge
jdk: openjdk8
#sudo: false

env:
  global:
      #travis encrypt -r gchq/event-logging GH_USER_AND_TOKEN="*****"
      #where ***** is '<github username>:<github personal access token>'
      #Required for curling the gh api to get the source of the latest event-logging release
    #- secure:"fWX4zkuQcHCHMjadg+3Fr13C4m9hwEMWqR1s9mmuxoU9cqV5n1Vv9Gj7gimc82UHgpaRwlfLOfdoLIvQRdUslH8DxrT16dmXnUnmm0NHEDCTC1t/19jExQNRi+jN8vB+KuvVztVTHEoBVb4SY15ca23JQKNMxv7hiC1C6ng5e+d90LWFj3xgaZzhjm3rBy3VlYbymWjhAEX+owncvdWQ8MEoLTgJYQ3uK+xG5rwtAt3Xc4YCbsTXteTdhnZ53WnPYTdZZ6yEegmv+PciBMnl5ypWyCmFvpHl9wMJ3VQRsv6ToI8rdfkIgrCs+mQ1pUrpV3IbR/JgL/uAmu6NW3GuIrLjv83ekvqdFCd9pQmh21JYemtj3Cxd8TJThCevlwP406+LUCZs13ysnbQsaf7PTnpUhiZs6xazWtj273HVGqYKAORfxkReax03V9AWuEyhxUk4e1QqpSwoX/nZ5Txyi6WfFkUJcuW/QgDKpacT7w5yD3ivkwxsCE1O2bn2rR+trG/Xz8dFH1D5uHGTBJD0mTvdjEsCI/lm/59sPgAYwiryJ/mD2wpGsgTJ9ucQD69j2jXeiph/UQ38H0qrl3QdPc5qlxjyZGPKpV7gl6TmXfMHf17SMR+6VKaGcg58MvYyaNNki8CC76ICJToOJY3v5VwL5CYLbBkdrxJeMqscN1w="
      #travis encrypt -r gchq/event-logging GH_USER_AND_TOKEN="<github personal access token>"
      #Required for curling the gh api to get the source of the latest event-logging release
    #- secure: "TOKbp0kSCBHm6xZHpmj28ZUPC4LpbZItn15Dcyk8sQ9EcYkFdwGEpD/qqkdA+9+GRCFIBmfvfHE1D5qKWICze5IYDgAgAabaDG3zygQ/W7WAyvVSO+4go6ZTZAhm/I/vJ6cwub47aYeV+OO4g+lZcTkWJpwBdJxRsXXFCXU5VRSoBc2hn2wUZuMpdyOpLb6Gs9QpJSnpRbOcXNIupJEc9t1LoO8dvXyJEL4sYLD1YiFammdDW+q/deaevTUJrsvXs1E8lSjyf/qZsUrJqYyzrnV2c2dPb/i/z2QYajPuJv5BlCjVFIROPV+JLepDDAMZGsjaXSNl8AxhYF2lXnQoTMCK8fkaINh2opGwhp7ksOXbpUM5B/x6bORl2wou75dsboMmzycQ08NlwzBrVZ7Lv33a3j02G5cwXKxkoP07VLixqaheOsEEJUINjQNrOuopqQA9v3jBecOBXIPs/SfJCTbu1/s9lFV9Vj5Lghn1VoHoG3n9dS9xPy9BDAf1dJCNNpfL+hDtVA9kx7haZ5Az2ueBMnrRF8TZJizyKvlK+EbXYayTGyxgNlHb6cUuQY0FcFzNnGPcxCvOaw0DW2gicFt1Flz7DYtjdj0037ExSIIm7EA1i9ucP5p/U5JASM66glE5IvnCREMzVZXxflhhEUUqbQ3lexvcZMoIgAl4ink="

install: echo "skip 'gradle assemble' step to speed up build"

script: ./travis.script.sh

# Push to GitHub releases - the key was generated by the Travis CLI.
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: event-logging-api/build/docs/javadoc/
    target_branch: gh-pages
    on:
      branch: master
  - provider: releases
    api_key:
      # travis encrypt -r gchq/event-logging <github personal access token>
      secure: "52OQP+PUgNzYCFyPCS2QmjCqjYfPVU0vHl+bq+p8cemfQeiwZN4k5eXKAyIexNBT7zkpSa/oDGNVIFYDkhZr0XAWEihOXHZklSR6G0v3wdYBx745QWsUrWhl/CL7wgfqj1GfgkpOQCblLbiA/CNA9N4bu1o+fCceyys2PqQHHG3gaszl/oaHLkjZmBLiRe+WSgDZIYCFBMu9AmiLws2NI7w4ocWU/dCKDscsBlH8qouiXdFCZNHb0Jc1C1/od5Vco/oowqx/POuYnwrsIi8AQeRVi88q7eZXZDAGzR62oHgjSG5LHJtM+bgrgk+S3jrpPRd6P4FxAc2VVrNZ+t+LQtyHJQf8UB2aTuXQ12pxoeA0X91jtJAZR3Ds3j+aF+raXsNVwgOqVOPtPWgOIuqf8tQ3pF8r3elMZOb1manZFq5q6YXBpw44mhTJW9UppKj4/FFGOKO6hwRe210JxKuvgpnyTjY9V7+tg9vTh1m3pIvcXG+/9l1lPNoUKmsHywf4QRxhXBhOBJI5jqrojA+fEa50t92tV5pezRydrAzzKIujo56+QfkytssL1l9FTd4L0bTawr0W2WpcAX+TL7KmN159RPzcd+edImL3xBAKVWtItcXhaeXlfde5au6rneWbYrYjMONSCYabVq12ev8nhdOaPOWhySNX6kgcre0igxY="
    file_glob: true
    file: event-logging-api/build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true

#clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
